### ISSUE TITLE
Take #3 MD5-PW multiple issues

### ISSUE THREAD

**Issue by job** [irrdnet/irrd-legacy#2]
@troy2914

There seem to be at least two issues of which one is directly related to your MD5-PW contribution. 
- Even when the access-list grants access to see the hashes, it shows the dumified versions
- After enabling pass hash hiding the maintainer cannot modifiy/add objects anymore

```
Sep  7 18:26:37 [4104] do_auth_check () cleartxt passwd-(unixcrypt_citesting) crypt passwd-($1$SaltSalt$DummifiedMD5HashValue.)
Sep  7 18:26:37 [4104] auth_ok () find_attr: (PGPKEY-8BFE94A9
)
Sep  7 18:26:37 [4104] auth_ok () find_attr: (test_001@localhost)
Sep  7 18:26:37 [4104] Syntax or authorization error.  Object not added to IRRd.
```

Previous run_tests.sh script didn't properly test your feature, here is example failure: https://travis-ci.org/job/irrd/builds/34648763

**Comment by troy2914** [comment]
Actually this does not appear to be related to the MD5-PW change, as the crypt test is failing too. 
see https://travis-ci.org/job/irrd/builds/34652898 where the failure occurs with the "INFO: testing object creation authenticated with UNIX crypt password" test, not the MD5 test.
