### ISSUE TITLE
by default prevent route-objects with origin 23456 from being created / accepted over NRTM

### ISSUE THREAD

**Issue by job** [irrdnet/irrd-legacy#26]
23456 probably never is a legit origin ASN

By default prevent route-objects with origin 23456 from being created / accepted over NRTM

**Comment by jaredmauch** [comment]
This should perhaps be an option that by default drops these objects and possibly also rejects the creation of objects using this origin ASN as well.  an AS-SET using this object should either flag the ASN as invalid or remove/ignore that component.
