### ISSUE TITLE
Version number should not start with 'v'

### ISSUE THREAD

**Issue by davidc** [irrdnet/irrd-legacy#29]
Version number reported to client must not start with 'v', thanks to this wonderful piece of code in irrtoolset to parse the version number!

   start = strstr(buffer, "version");
   start = start + 8; //jump
   version = atoi(start)*10 + atoi(start+2); // x.x... format

**Comment by job** [comment]
`src/configure.ac` and `src/Make.include.in` will need a fix.

**Comment by haussli** [comment]
d9194a9a9368c1607ce3a8453a13e4e2328f7ddc
