### ISSUE TITLE
Doesn't work !i(as-set) query correctly with multiple source(!s) was specified

### ISSUE THREAD

**Issue by a16** [irrdnet/irrd-legacy#33]
Hi,

It doesn't seems that the query with !i option works correctly after multiple source was specified using !s in multiple-command mode.
Is it a known bug?

For example,

```
% telnet whois.radb.net 43
!!
!sRIPE
C
!iAS-NETNOD,1
A167
AS112 AS199670 AS201965 AS20943 AS21239 AS24406 AS25192 AS29216 AS31529 AS35052 AS36625 AS39840 AS39870 AS39871 AS49488 AS51966 AS56266 AS56625 AS56908 AS57021 AS8674
C
!sAPNIC
C
!iAS-NETNOD,1
A61
AS112 AS20943 AS25192 AS29216 AS31529 AS36625 AS56266 AS8674
C
```

It works fine when single source was specified. :-)

```
!sRIPE,APNIC
C
!iAS-NETNOD,1
A167
AS112 AS199670 AS201965 AS20943 AS21239 AS24406 AS25192 AS29216 AS31529 AS35052 AS36625 AS39840 AS39870 AS39871 AS49488 AS51966 AS56266 AS56625 AS56908 AS57021 AS8674
C
!sAPNIC,RIPE
C
!iAS-NETNOD,1
A61
AS112 AS20943 AS25192 AS29216 AS31529 AS36625 AS56266 AS8674
C
```

The first source only seems to be used. So the result will be depends on the order of sources. :(

**Comment by haussli** [comment]
It returns the first match based on the order of the databases in the configuration of the server; as far as I know, it has always worked this way.
