### ISSUE TITLE
irrd-user.pdf is unreadable in Chrome

### ISSUE THREAD

**Issue by devicenull** [irrdnet/irrd-legacy#38]
It seems that Chrome's PDF reader is eating all the newlines in irrd-user.pdf, making it an unreadable blob of text

**Comment by tangledhelix** [comment]
This is not limited to Chrome. I see the same result in Safari (Mac), and if cloning the repo (no browser involved), the PDF still renders poorly in a standalone PDF viewer.

**Comment by job** [comment]
@erikr was kind enough to fix this through https://github.com/irrdnet/irrd/commit/da828ea5868a82307b5008c49960558c1e4b9d2a
