### ISSUE TITLE
irr_notify gives error "*****No sendmail or mail binary found on system!***"

### ISSUE THREAD

**Issue by tejasbelur** [irrdnet/irrd-legacy#41]
When irr_notify program tries to send notification email for object updates in routing db the following error message is logged in submission.log file:

Feb  3 13:46:50 [8209] *****No sendmail or mail binary found on system!***
Feb  3 13:46:50 [8209] *****No notifications will be sent***

The config .log has the following logged for sendmail program/command:
[abc@xyz]$ grep -i sendmail  config.log
configure:4354: checking for sendmail
configure:4373: found /usr/sbin/sendmail
configure:4386: result: /usr/sbin/sendmail
| #define HAVE_SENDMAIL 1
| #define HAVE_SENDMAIL 1
| #define HAVE_SENDMAIL 1
ac_cv_path_SENDMAIL_PATH=/usr/sbin/sendmail
SENDMAIL_PATH='/usr/sbin/sendmail'
#define HAVE_SENDMAIL 1

the location of sendmail is as follows:
[abc@xyz]$ ll /usr/sbin/sendmail
lrwxrwxrwx 1 root root 21 Jun  3  2016 /usr/sbin/sendmail -> /etc/alternatives/mta
[abc@xyz]$ ll /etc/alternatives/mta
lrwxrwxrwx 1 root root 27 Jun  3  2016 /etc/alternatives/mta -> /usr/sbin/sendmail.sendmail
[abc@xyz]$ ll /usr/sbin/sendmail.sendmail
-rwxr-sr-x 1 root smmsp 833512 Jun 17  2010 /usr/sbin/sendmail.sendmail

Please let me know how this issue can be resolved? This issue is for irrd version 2.3.10.

**Comment by haussli** [comment]
Fri, Feb 03, 2017 at 05:57:18AM -0800, Tejas Belur:
> When irr_notify program tries to send notification email for object updates in routing db the following error message is logged in submission.log file:
> 
> Feb  3 13:46:50 [8209] *****No sendmail or mail binary found on system!***
> Feb  3 13:46:50 [8209] *****No notifications will be sent***
> 
> The config .log has the following logged for sendmail program/command:
> [abc@xyz]$ grep -i sendmail  config.log
> configure:4354: checking for sendmail
> configure:4373: found /usr/sbin/sendmail
> configure:4386: result: /usr/sbin/sendmail
> | #define HAVE_SENDMAIL 1
> | #define HAVE_SENDMAIL 1
> | #define HAVE_SENDMAIL 1
> ac_cv_path_SENDMAIL_PATH=/usr/sbin/sendmail
> SENDMAIL_PATH='/usr/sbin/sendmail'
> #define HAVE_SENDMAIL 1
> 
> the location of sendmail is as follows:
> [abc@xyz]$ ll /usr/sbin/sendmail
> lrwxrwxrwx 1 root root 21 Jun  3  2016 /usr/sbin/sendmail -> /etc/alternatives/mta
> [abc@xyz]$ ll /etc/alternatives/mta
> lrwxrwxrwx 1 root root 27 Jun  3  2016 /etc/alternatives/mta -> /usr/sbin/sendmail.sendmail
> [abc@xyz]$ ll /usr/sbin/sendmail.sendmail
> -rwxr-sr-x 1 root smmsp 833512 Jun 17  2010 /usr/sbin/sendmail.sendmail
> 
> 
> Please let me know how this issue can be resolved? This issue is for irrd version 2.3.10.

can you move forward to 3.0.8?

**Comment by tejasbelur** [comment]
Thanks for your quick response. Installed 3.0.8 but still the same error is persisting. Details below:

[abc@xyz sbin]$ tail -n 5 /var/log/irrd/submission.log
Feb  6 04:24:00 [23651] NO CHANGE: [route] 65.49.224.0/22 AS38621
Feb  6 04:24:00 [23651] *****No sendmail or mail binary found on system!***
Feb  6 04:24:00 [23651] *****No notifications will be sent***
Feb  6 04:24:00 [23651]

[abc@xyz sbin]$ irrd -version
irrd: invalid option -- 'e'
Usage: irrd
   [-a turn on atomic transaction mode]
   [-d <irr_directory>]
   [-f <irrd.conf file>]
   [-g <groupname>]
   [-l <username>]
   [-n do not daemonize]
   [-s <password>]
   [-u don't allow privileged commands]
   [-v verbose mode]
   [-w <irr_port>]
   [-x cancel bootstrap missing DB auto-fetch]

IRRd 3.0.8 [25Apr2014] compiled on Feb  5 2017
[abc@xyz sbin]$

**Comment by tejasbelur** [comment]
Hi @haussli , this is a bit urgent issue and hence it would be great if you can guide on the resolution - whether code issue or config issue or whether I need to raise issue via some other channel. Thanks in advance!
