### ISSUE TITLE
"make install" fails for non-root

### ISSUE THREAD

**Issue by ssinyagin** [irrdnet/irrd-legacy#45]
programs/irr_notify/Makefile has a hardcoded owner and group in install target: `-o root -g bin`. 

So, a non-root user has to modify the Makefile to make the installation complete. In our environment, root user is not allowed by IT, and I believe it's quite common in many places.

So, the installuser should be defined within "configure" script.

**Comment by job** [comment]
Pull request is welcome

**Comment by ssinyagin** [comment]
I'll make one as soon as #44 is resolved. Also I'll make an update on .gitignore, as there are many files that git shows in 'git status' after compiling.
