### ISSUE TITLE
make can not find aclocal-1.15

### ISSUE THREAD

**Issue by randyqx** [irrdnet/irrd-legacy#53]
after `make clean` and `./configure`

```work0.psg.com:/usr/local/src/net/irrd/src# make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /usr/local/src/net/irrd/src/aconf/missing aclocal-1.15 -I m4
/usr/local/src/net/irrd/src/aconf/missing: aclocal-1.15: not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
*** Error code 127

Stop.
make: stopped in /usr/local/src/net/irrd/src

work0.psg.com:/usr/local/src/net/irrd/src# pkg install automake
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The most recent versions of packages are already installed

work0.psg.com:/usr/local/src/net/irrd/src# pkg install autoconf
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The most recent versions of packages are already installed

work0.psg.com:/usr/local/src/net/irrd/src# automake
configure.ac:10: error: version mismatch.  This is Automake 1.16.2,
configure.ac:10: but the definition used by this AM_INIT_AUTOMAKE
configure.ac:10: comes from Automake 1.15.  You should recreate
configure.ac:10: aclocal.m4 with aclocal and run automake again.```

**Comment by haussli** [comment]
> work0.psg.com:/usr/local/src/net/irrd/src# automake
> configure.ac:10: error: version mismatch.  This is Automake 1.16.2,
> configure.ac:10: but the definition used by this AM_INIT_AUTOMAKE
> configure.ac:10: comes from Automake 1.15.  You should recreate
> configure.ac:10: aclocal.m4 with aclocal and run automake again.```

This is precisely why I agrue against having users run autoconf.  It
leads to more support work.  All the autoconf should be included in the
repo & dist.

**Comment by job** [comment]
@haussli we don't know what version or git checkout the user tried this on. Afaik we include autoconf in the dist...  (but it has been a while since we released an irrd 3 version, most effort went to irrd v4)

**Comment by haussli** [comment]
I do not understand the connection.  whatever version they checkout is the
version of the autoconf scripts they receive - the scripts, not the result
of the scripts.

**Comment by haussli** [comment]
because of the version?  I know this seems to have become common practice,
but I say stop doing that, its stupid.  the support cost savings is far
greater than the git version being in the autoconf scripts - and it is
irrrelevant.  put the git version in a separate include created by make,
if you must have it in executables - the installed stuff.
